name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore knoriX-release.keystore \
            -alias knoriX \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass KnoriX@mvpTest \
            -keypass KnoriX@mvpTest \
            -dname "CN=KnoriX, OU=Dev, O=KnoriX, L=India, S=India, C=IN"

      - name: Print Base64
        run: |
          echo "========= COPY THIS ========="
          base64 knoriX-release.keystore
          echo "========= END ========="
